# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-03 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField()),
                ('language', models.CharField(max_length=20)),
                ('input', models.TextField()),
                ('compile_status', models.CharField(max_length=50)),
                ('run_status', models.CharField(max_length=50)),
                ('run_time', models.CharField(max_length=10)),
                ('run_memory', models.CharField(max_length=10)),
                ('output', models.TextField()),
                ('run_stderr', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Code',
                'ordering': ['timestamp'],
                'verbose_name_plural': 'Codes',
            },
        ),
    ]
