# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-03 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='run_stderr',
        ),
        migrations.AddField(
            model_name='code',
            name='web_link',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
