# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-03 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0002_auto_20180603_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='output',
            new_name='output_html',
        ),
        migrations.RemoveField(
            model_name='code',
            name='web_link',
        ),
    ]
